version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
  api:
    build: ./api
    depends_on: [db]
    environment:
      DB_HOST: db
    ports:
      - "3001:3001"
  web:
    build: ./web
    depends_on: [api]
    ports:
      - "3000:3000"
